set(VCPKG_CMAKE_SYSTEM_VERSION 6.1)
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_BUILD_TYPE release)

set(VCPKG_C_FLAGS "/DWINVER=0x0601 /D_WIN32_WINNT=0x0601 /DNTDDI_VERSION=0x06010000")

if(DEFINED VCPKG_C_FLAGS AND NOT DEFINED VCPKG_CXX_FLAGS)
  set(VCPKG_CXX_FLAGS "${VCPKG_C_FLAGS}")
endif()
